assignment6-lighting.out: assignment6-lighting.cpp ../glad.o
	g++ -lglfw -framework OpenGL -o assignment6-lighting.out assignment6-lighting.cpp ../glad.o

.PHONY: clean
clean:
	rm assignment6-lighting.out
