assignment4-rotatingsquare.out: assignment4-rotatingsquare.cpp ../glad.o
	g++ -lglfw -framework OpenGL -o assignment4-rotatingsquare.out assignment4-rotatingsquare.cpp ../glad.o

.PHONY: clean
clean:
	rm assignment4-rotatingsquare.out
